// Code generated by mockery v1.0.0. DO NOT EDIT.

package events

import (
	"github.com/almaznur91/splitty/internal/api"
	mock "github.com/stretchr/testify/mock"
)

// mockMsgLogger is an autogenerated mock type for the msgLogger type
type mockMsgLogger struct {
	mock.Mock
}

// Save provides a mock function with given fields: msg
func (_m *mockMsgLogger) Save(msg *api.Message) {
	_m.Called(msg)
}
