// Code generated by mockery v1.0.0. DO NOT EDIT.

package bot

import (
	"github.com/almaznur91/splitty/internal/api"
	mock "github.com/stretchr/testify/mock"
)

// MockInterface is an autogenerated mock type for the Interface type
type MockInterface struct {
	mock.Mock
}

// Help provides a mock function with given fields:
func (_m *MockInterface) Help() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// OnMessage provides a mock function with given fields: msg
func (_m *MockInterface) OnMessage(msg api.Message) api.Response {
	ret := _m.Called(msg)

	var r0 api.Response
	if rf, ok := ret.Get(0).(func(api.Message) api.Response); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Get(0).(api.Response)
	}

	return r0
}

// ReactOn provides a mock function with given fields:
func (_m *MockInterface) ReactOn() []string {
	ret := _m.Called()

	var r0 []string
	if rf, ok := ret.Get(0).(func() []string); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	return r0
}
