name: Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.15
        uses: actions/setup-go@v1
        with:
          go-version: 1.15
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build
        run: make build

      - name: Lint
        run: |
          go run github.com/golangci/golangci-lint/cmd/golangci-lint run
          go get -u golang.org/x/lint/golint
          /home/runner/go/bin/golint

  publish:
    if: github.event_name == 'push' && (contains(github.ref, 'develop') || contains(github.ref, 'master'))
    runs-on: ubuntu-latest
    needs: [ build ]
    name: Push docker image
    steps:
       - name: Set up QEMU
         uses: docker/setup-qemu-action@v1
       - name: Docker meta adapter
         id: docker_meta
         uses: crazy-max/ghaction-docker-meta@v1
         with:
           tag-match: \d{1,3}.\d{1,3}.\d{1,3}
           images: zagamaza/splitty
           tag-sha: true # add git short SHA as Docker tag
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v1
       - name: Login to DockerHub
         uses: docker/login-action@v1
         with:
           username: ${{ secrets.DOCKER_LOGIN }}
           password: ${{ secrets.DOCKER_PASSWORD }}
       - name: Build and push
         id: docker_build
         uses: docker/build-push-action@v2
         with:
           push: true
           tags: ${{ steps.docker_meta.outputs.tags }}
           labels: ${{ steps.docker_meta.outputs.labels }}
       - name: Image digest
         run: echo ${{ steps.docker_build.outputs.digest }}
